export enum CardIds {
    Northguards = 253,
    Thugs = 254,
    Enforcer = 255,
    Defenders = 256,
    Tremor = 287,
    MasterArchers = 288,
    Emberstrike = 289,
    Juggernaut = 290,
    Wrathblades = 301,
    RifleCultists = 302,
    Forsaken = 303,
    Harvester = 304,
    SkeletonWarriors = 305,
    Construct = 316,
    Coldsnap = 344,
    SurgeOfLight = 345,
    Sunstriders = 346,
    Eruption = 354,
    Inferno = 355,
    Imperials = 356,
    WhiteRangers = 357,
    Phalanx = 359,
    Spearmen = 361,
    Windweavers = 362,
    FrostSorceress = 364,
    IceGuardian = 365,
    SilverwindLancers = 366,
    FrostMage = 367,
    LyrishKnight = 368,
    KoboldEngineer = 370,
    Rageclaws = 372,
    Wrecker = 373,
    MagmaSpore = 374,
    Sunderer = 375,
    Strikers = 376,
    ScytheFiends = 377,
    Firedancer = 378,
    MagmaHurler = 379,
    Virtuoso = 380,
    BoomBrothers = 386,
    GiantSlayer = 387,
    Moloch = 388,
    TimelessOne = 402,
    NoxTrooper = 404,
    ShadowMage = 405,
    Executor = 406,
    MutatingFrenzy = 407,
    AshbonePyro = 408,
    Vulcan = 413,
    Battleship = 414,
    GroveSpirit = 415,
    Shaman = 416,
    Mauler = 417,
    FathomLord = 418,
    Colossus = 419,
    Spikeroot = 420,
    Thornbark = 421,
    DeathRay = 426,
    EnergyParasite = 427,
    ParasiteSwarm = 431,
    LivingTower = 432,
    Nightcrawler = 434,
    Burrower = 442,
    Drones = 443,
    ShadowInsect = 444,
    WinterWitch = 507,
    SkyelfTemplar = 524,
    SkyelfCommander = 526,
    SkyelfSage = 527,
    Tempest = 529,
    MagmaFiend = 534,
    ShrineofMartyrs = 536,
    IceShieldTower = 538,
    KoboldLaboratory = 539,
    DefenseTower = 540,
    ShrineofWar = 541,
    MakeshiftTower = 542,
    FireBomb = 543,
    MortarTower = 544,
    Werebeasts = 546,
    Ghostspears = 547,
    Razorleaf = 548,
    SporeLauncher = 549,
    PrimevalWatcher = 550,
    TimeshifterSpirit = 552,
    ShrineofMemory = 553,
    WheelofGifts = 554,
    Tunnel = 555,
    FountainofRebirth = 556,
    HealingWell = 557,
    DarkelfAssassins = 558,
    Ripper = 559,
    UnstableDemon = 560,
    Overlord = 561,
    CultistMaster = 562,
    Necrofury = 563,
    Wrathgazer = 564,
    ShrineofGreed = 565,
    Decomposer = 566,
    PortalNexus = 567,
    FrostCrystal = 573,
    CorpseExplosion = 618,
    RayofLight = 619,
    GlacierShell = 620,
    Stronghold = 647,
    ResourceBooster = 648,
    AltarofChaos = 649,
    FurnaceofFlesh = 650,
    Lifestealer = 651,
    WarEagle = 661,
    ManaWing = 662,
    ShadowPhoenix = 663,
    FallenSkyelf = 664,
    Scavenger = 672,
    FireStalker = 673,
    Swiftclaw = 674,
    FireDragon = 677,
    Dreadnought = 682,
    AvatarofFrost = 683,
    CannonTower = 700,
    CreepingParalysis = 702,
    SkyfireDrake = 703,
    PrimalDefender = 705,
    Dreadcharger = 706,
    SwampDrake = 707,
    GiantWyrm = 708,
    FireWorm = 709,
    AuraofCorruption = 716,
    PhaseTower = 717,
    Grimvine = 718,
    DeepcoilWorm = 719,
    ShadowWorm = 720,
    RallyingBanner = 723,
    Thunderstorm = 724,
    Earthshaker = 726,
    KoboldTrick = 728,
    Wallbreaker = 738,
    WardoftheNorth = 739,
    NastySurprise = 740,
    AuraofPain = 741,
    AreaIceShield = 744,
    TowerofFlames = 745,
    FrostShard = 746,
    Maelstrom = 747,
    NoxiousCloud = 749,
    EnsnaringRoots = 750,
    ArmoredTower = 751,
    TermiteHill = 770,
    JuiceTank = 771,
    WorldbreakerGun = 772,
    CometCatcher = 773,
    MorklayTrap = 774,
    RocketTower = 776,
    Spitfire = 778,
    ConstructionHut = 781,
    BreedingGrounds = 782,
    VoidMaw = 784,
    Mountaineer = 786,
    IceBarrier = 787,
    MarkoftheKeeper = 788,
    HomeSoil = 789,
    Infect = 793,
    Soulshatter = 794,
    Parasite = 796,
    Lifestream = 801,
    EmbalmersShrine = 814,
    HealingGardens = 815,
    StoneofTorment = 816,
    Regrowth = 819,
    LavaField = 820,
    GlyphofFrost = 826,
    ShieldBuilding = 827,
    BloodHealing = 828,
    UnholyHero = 829,
    Suppression = 830,
    PlagueOld = 831,
    MindControl = 833,
    Mine = 834,
    RetreatingCircle = 835,
    UnholyPower = 836,
    Bloodthirst = 838,
    Mindweaver = 839,
    VoodooShack = 840,
    Backlash = 841,
    AltarofNihil = 862,
    Voidstorm = 932,
    BannerofGlory = 933,
    IceTornado = 938,
    Wildfire = 957,
    Ravage = 962,
    Enlightenment = 968,
    ShatterIce = 969,
    Motivate = 970,
    Hurricane = 972,
    UndeadArmy = 977,
    Revenge = 978,
    LifeWeaving = 979,
    ChurchofNegation = 1003,
    CurseofOink = 1004,
    FiredancerPromo = 1021,
    JuggernautPromo = 1029,
    RazorleafPromo = 1030,
    SwampDrakePromo = 1031,
    LyrishKnightPromo = 1032,
    ConstructPromo = 1033,
    FallenSkyelfPromo = 1034,
    HarvesterPromo = 1035,
    LightbladeAShadow = 1117,
    StormsingerAFire = 1119,
    CoreDredgeAFrost = 1120,
    NomadAFire = 1121,
    GladiatrixANature = 1122,
    SpiritHuntersANature = 1123,
    ThunderWagonAFire = 1124,
    AmazonAFrost = 1126,
    ForestElderANature = 1128,
    Nightguard = 1129,
    NoxCarrierAFire = 1131,
    SnapjawsAFire = 1132,
    MatterMasteryANature = 1162,
    NorthstarAFrost = 1163,
    FrontierKeepAFrost = 1164,
    BlasterCannonAFire = 1165,
    InfernalMachineAShadow = 1166,
    RootNexusANature = 1167,
    HowlingShrineANature = 1168,
    SoulSplicerANature = 1169,
    TimeVortexAShadow = 1170,
    BloodhornAShadow = 1171,
    StoneTempestAFrost = 1181,
    CurseOrb = 1182,
    RageflameAFrost = 1183,
    OfferingANature = 1184,
    BanditLauncherAFire = 1185,
    GravitySurgeAFrost = 1186,
    NetherWarpAFrost = 1187,
    DisenchantAShadow = 1189,
    StoneShardsAFrost = 1191,
    CrystalFiendANature = 1192,
    AggressorANature = 1193,
    StoneWarriorAFrost = 1194,
    GrinderAShadow = 1195,
    GemeyeAShadow = 1196,
    CommandosAShadow = 1197,
    BanditosANature = 1198,
    BanditStalkerAShadow = 1199,
    WindhunterAShadow = 1200,
    CorsairANature = 1201,
    GunnerAFire = 1202,
    TortugunAFrost = 1203,
    SkydefenderAShadow = 1204,
    WaystationAFire = 1205,
    ArtilleryAShadow = 1206,
    StoneLauncherAFrost = 1207,
    StoneHurlerAFire = 1208,
    HammerfallANature = 1209,
    DeepgorgeAFrost = 1210,
    ScorchedEarthAFire = 1214,
    VilebloodAFire = 1219,
    SlaverAFire = 1220,
    TwilightMinionsAFire = 1221,
    EnvenomAShadow = 1222,
    EquilibriumAFrost = 1223,
    DeathgliderANature = 1224,
    MutatingManiacANature = 1225,
    SkycatcherANature = 1226,
    NightshadePlantANature = 1227,
    TwilightCreeperAFire = 1228,
    AmiiRitualAFrost = 1229,
    TwilightBombardAFire = 1230,
    HatecasterAShadow = 1231,
    FleshbenderAShadow = 1232,
    WillzapperAFire = 1233,
    KnightOfChaosAFrost = 1235,
    IcefangRaptorAFire = 1236,
    FireswornAFrost = 1237,
    SunReaverAFire = 1238,
    DryadANature = 1239,
    DeepOneANature = 1240,
    WitchclawsAShadow = 1241,
    FrostBiteAShadow = 1242,
    EarthenGiftAFire = 1243,
    UnityANature = 1244,
    AmokAFire = 1254,
    PromiseofLifeANature = 1255,
    SecondChanceANature = 1256,
    Mo = 1262,
    Viridya = 1263,
    RoganKayle = 1264,
    Ravenheart = 1265,
    LightbladeAFire = 1267,
    NorthstarANature = 1273,
    MoPromo = 1274,
    ViridyaPromo = 1275,
    RoganKaylePromo = 1276,
    RavenheartPromo = 1277,
    StormsingerANature = 1278,
    CoreDredgeAFire = 1279,
    FrontierKeepAFire = 1280,
    GravitySurgeAShadow = 1281,
    AmiiRitualANature = 1282,
    FrostBiteAFire = 1283,
    NomadANature = 1284,
    GladiatrixAShadow = 1285,
    ThunderWagonAShadow = 1286,
    BlasterCannonAShadow = 1287,
    InfernalMachineAFire = 1288,
    DisenchantANature = 1290,
    ScorchedEarth = 1291,
    UnityAFrost = 1292,
    ForestElderAShadow = 1293,
    AmazonANature = 1294,
    SpiritHuntersAShadow = 1295,
    TortugunAFire = 1296,
    BloodhornAFire = 1297,
    NightguardANature = 1298,
    GrinderAFire = 1299,
    RageflameAFire = 1300,
    RootNexusAFrost = 1301,
    HowlingShrineAShadow = 1302,
    EnvenomAFire = 1303,
    EquilibriumANature = 1304,
    PromiseofLifeAFrost = 1305,
    NoxCarrierAShadow = 1306,
    SnapjawsAShadow = 1307,
    SoulSplicerAFire = 1308,
    TimeVortexAFrost = 1309,
    NetherWarpANature = 1310,
    OfferingAFrost = 1311,
    SecondChanceAShadow = 1312,
    CommandosAFrost = 1313,
    BanditosAFrost = 1315,
    BanditStalkerANature = 1316,
    WindhunterANature = 1317,
    CorsairAShadow = 1318,
    GunnerAShadow = 1319,
    BanditLauncherAShadow = 1320,
    SkydefenderANature = 1321,
    WaystationAShadow = 1322,
    ArtilleryAFire = 1324,
    StoneTempestAShadow = 1325,
    StoneShardsAFire = 1326,
    CrystalFiendAFrost = 1327,
    SandstormAFire = 1328,
    AmokANature = 1329,
    GemeyeANature = 1330,
    AggressorAFrost = 1331,
    MatterMasteryAShadow = 1332,
    StoneWarriorANature = 1333,
    EarthenGiftAShadow = 1334,
    StoneLauncherAShadow = 1335,
    StoneHurlerAShadow = 1336,
    HammerfallAFrost = 1337,
    DeepgorgeAFire = 1338,
    SandstormAShadow = 1339,
    NorthlandDrakeAFire = 1343,
    BatarielAFire = 1344,
    GrimBahirAFire = 1345,
    IroncladAFrost = 1346,
    AbyssalWarderAFrost = 1347,
    SatanaelAFire = 1348,
    LostWarlordAFire = 1361,
    BurrowRitualANature = 1372,
    DeepOneAShadow = 1375,
    StrangleholdAShadow = 1376,
    StrangleholdANature = 1377,
    PyromaniacAFrost = 1379,
    PyromaniacAFire = 1380,
    KnightOfChaosAShadow = 1382,
    SatanaelAShadow = 1385,
    FireswornAFire = 1386,
    BurrowRitualAFire = 1389,
    DryadAFrost = 1391,
    IncubatorAFire = 1392,
    WardensSigilANature = 1394,
    WardensSigilAFrost = 1395,
    KoboldIncAFrost = 1397,
    VolcanoAFire = 1398,
    IncubatorAShadow = 1399,
    SylvanGateAFire = 1401,
    NecroblasterAShadow = 1402,
    GrimBahirANature = 1409,
    LostWandererANature = 1410,
    LostShadeAFrost = 1411,
    LostDancer = 1412,
    LostReaverAFire = 1413,
    LostVigilANature = 1414,
    LostSpiritShipANature = 1415,
    LostGrigoriAShadow = 1416,
    VilebloodANature = 1428,
    SlaverAShadow = 1429,
    LostLauncherAFire = 1430,
    LostDisruptorANature = 1431,
    LostConverterAFrost = 1432,
    LostBanestoneANature = 1433,
    LostShadeAShadow = 1434,
    LostReaverAShadow = 1436,
    LostVigilAShadow = 1438,
    ArchitectsCallAFrost = 1439,
    LostDisruptorAShadow = 1440,
    LostWarlordAFrost = 1442,
    LostGrigoriAFire = 1443,
    TwilightCurseAShadow = 1444,
    TwilightCurseAFire = 1447,
    ArchitectsCallAShadow = 1448,
    IroncladAFire = 1449,
    SantaClaus = 1450,
    MutatingManiacAFire = 1451,
    KoboldIncAShadow = 1458,
    BatarielAShadow = 1465,
    EvocatorsWoeAShadow = 1466,
    EvocatorsWoeANature = 1467,
    IcefangRaptorAFrost = 1468,
    DyingBreedAShadow = 1469,
    DyingBreedANature = 1470,
    SylvanGateAFrost = 1471,
    LostWandererAFrost = 1472,
    SunReaverANature = 1474,
    ForestsVimAShadow = 1475,
    AbyssalWarderAFire = 1477,
    LostDancerAFire = 1480,
    NorthlandDrakeAFrost = 1482,
    IceAgeAFrost = 1483,
    NightshadePlantAShadow = 1484,
    TwilightMinionsANature = 1485,
    DeathgliderAFrost = 1486,
    SkycatcherAFrost = 1487,
    WillzapperAShadow = 1488,
    TwilightCreeperAShadow = 1489,
    FleshbenderAFire = 1490,
    NecroblasterANature = 1495,
    IceAgeANature = 1496,
    VolcanoANature = 1497,
    GlobalWarmingAFrost = 1498,
    GlobalWarmingAFire = 1499,
    GlaciationAFire = 1500,
    GlaciationAFrost = 1501,
    RevenantsBlessing = 1502,
    RevenantsBlessingANature = 1503,
    LostSpiritShipAFire = 1505,
    LostBanestoneAFrost = 1508,
    LostLauncherAFrost = 1509,
    HatecasterANature = 1510,
    TwilightBombardAFrost = 1511,
    LostConverter = 1512,
    ProtectorsSealLS = 1513,
    ProtectorsSealT = 1514,
    GreenPeaceAFire = 1515,
    GreenPeaceAFrost = 1516,
    ForestsVimANature = 1517,
    InfernalChainANature = 1518,
    InfernalChainAFrost = 1519,
    ClusterExplosionAShadow = 1520,
    ClusterExplosionAFire = 1521,
    LostEvocationAFire = 1522,
    LostEvocationAFrost = 1525,
    TwilightPestilenceANature = 1526,
    TwilightPestilenceAFrost = 1527,
    BefallensCurseAShadow = 1528,
    BefallensCurseAFire = 1529,
    CurseWell = 1530,
    QueekQueek = 1531,
    Moon = 1532,
    Jorne = 1533,
    WarlockAFire = 1536,
    TreespiritAShadow = 1537,
    MountainRowdyAShadow = 1538,
    WitchclawsAFire = 1539,
    WarlockAFrost = 1540,
    TreespiritANature = 1541,
    LostPriest = 1542,
    LostHorrorANature = 1543,
    LostDragonANature = 1544,
    LostDragonAShadow = 1545,
    BanditSpearmenAFire = 1548,
    BanditSpearmenAFrost = 1549,
    MountainRowdyAFrost = 1550,
    LostPriestAShadow = 1552,
    TwilightBruteAFire = 1554,
    TwilightBruteANature = 1555,
    LostHorrorAFire = 1558,
    AbominationAFrost = 1561,
    AbominationAShadow = 1562,
    SoulhunterAFrost = 1563,
    SoulhunterAShadow = 1564,
    Deepfang = 1565,
    DeepfangANature = 1567,
    BanditLancerAShadow = 1568,
    BanditLancerANature = 1569,
    EarthkeeperAFrost = 1570,
    EarthkeeperAFire = 1571,
    OracleMaskANature = 1572,
    RazorshardAFire = 1573,
    RazorshardANature = 1574,
    TreefiendAShadow = 1575,
    TreefiendANature = 1576,
    OracleMaskAFire = 1577,
    TheIncredibleMo = 1578,
    FreneticAssaultANature = 1579,
    MumboJumboAShadow = 1580,
    MumboJumboAFire = 1581,
    FreneticAssaultAShadow = 1582,
    NorthernKeepAFire = 1583,
    SunkenTempleAShadow = 1584,
    EasterEgg = 1585,
    WintertideAFrost = 1586,
    WintertideAFire = 1587,
    TwilightWarfareAFire = 1588,
    AmiiMonument = 1589,
    TwilightWarfareAShadow = 1590,
    SunkenTempleANature = 1592,
    FlameCrystal = 1595,
    EarthCrystal = 1596,
    IceCrystal = 1597,
    DarkCrystal = 1598,
    NorthernKeepAFrost = 1599,
    InfectedTowerAFire = 1600,
    InfectedTowerAFrost = 1604,
    RiotersRetreatANature = 1605,
    RiotersRetreatAFrost = 1606,
    GrinderAShadowPromo = 1607,
    StoneShellAShadow = 1608,
    StoneShellANature = 1610,
    EtherealStormAFire = 1611,
    EtherealStormAFrost = 1612,
    WarriorsDeathAFire = 1613,
    WarriorsDeathAFrost = 1614,
    LordCyrian = 1615,
    BanditSorceressAFrost = 1616,
    GirlPowerAFrost = 1617,
    GirlPower = 1618,
    TwilightHagANature = 1619,
    BanditSorceressAFire = 1620,
    TwilightHagAFire = 1622,
    Brannoc = 1624,
    EliminatorAFire = 1628,
    EliminatorAFrost = 1629,
    SantaClausWithPresents = 1639,
    AmiiPhantom = 1640,
    SnapjawsAFirePromo = 1642,
    FireSphere = 1664,
    Plague = 1665,
    AmiiPaladins = 1666,
    CoatOfProtectionAFrost = 1667,
    CoatOfProtectionAShadow = 1668,
    BanditSniper = 1669,
    BanditMinefield = 1670,
    BanzaiLordAShadow = 1671,
    BanzaiLordANature = 1673,
    ManaWingPromo = 1675,
    BurningSpears = 1676,
    Transcendence = 1677,
    WastelandTerrorAFire = 1678,
    WastelandTerrorANature = 1679,
    TwilightCrawlers = 1680,
    TwilightSlayersAFire = 1681,
    TwilightSlayersAShadow = 1682,
    Tranquility = 1683,
    EvilEye = 1684,
    SanctuaryAFrost = 1685,
    SanctuaryANature = 1686,
    RavenArchwalker = 1687,
    WorldbreakerGunPromo = 1688,
    SleetStorm = 1689,
    Soulstone = 1690,
    TectonicShift = 1691,
    GateOfAkylos = 1692,
    LostManabeast = 1693,
    BedrockAFrost = 1695,
    BedrockAShadow = 1696,
    Swarm = 1697,
    Icespike = 1698,
    Umbabwe = 1699,
    AmiiSentinel = 1700,
    EnergyCore = 1701,
    Skydancer = 1702,
    Simulacrum = 1703,
    JornePromo = 1704,
    TwilightArchers = 1705,
    PowerShrine = 1706,
    BanditHut = 1707,
    Molt = 1709,
    Hellhound = 1710,
    SpiritGate = 1711,
    FrostMagePromo = 1712,
    Devourer = 1713,
    TreasureWagon = 1714,
    SundererPromo = 1715,
}

export const allCardIds: CardIds[] = Object.values(CardIds).filter(v => typeof v !== 'string');

export const allCards: {[key: string]: CardIds;} = {
    Northguards: CardIds.Northguards,
    Thugs: CardIds.Thugs,
    Enforcer: CardIds.Enforcer,
    Defenders: CardIds.Defenders,
    Tremor: CardIds.Tremor,
    MasterArchers: CardIds.MasterArchers,
    Emberstrike: CardIds.Emberstrike,
    Juggernaut: CardIds.Juggernaut,
    Wrathblades: CardIds.Wrathblades,
    RifleCultists: CardIds.RifleCultists,
    Forsaken: CardIds.Forsaken,
    Harvester: CardIds.Harvester,
    SkeletonWarriors: CardIds.SkeletonWarriors,
    Construct: CardIds.Construct,
    Coldsnap: CardIds.Coldsnap,
    SurgeOfLight: CardIds.SurgeOfLight,
    Sunstriders: CardIds.Sunstriders,
    Eruption: CardIds.Eruption,
    Inferno: CardIds.Inferno,
    Imperials: CardIds.Imperials,
    WhiteRangers: CardIds.WhiteRangers,
    Phalanx: CardIds.Phalanx,
    Spearmen: CardIds.Spearmen,
    Windweavers: CardIds.Windweavers,
    FrostSorceress: CardIds.FrostSorceress,
    IceGuardian: CardIds.IceGuardian,
    SilverwindLancers: CardIds.SilverwindLancers,
    FrostMage: CardIds.FrostMage,
    LyrishKnight: CardIds.LyrishKnight,
    KoboldEngineer: CardIds.KoboldEngineer,
    Rageclaws: CardIds.Rageclaws,
    Wrecker: CardIds.Wrecker,
    MagmaSpore: CardIds.MagmaSpore,
    Sunderer: CardIds.Sunderer,
    Strikers: CardIds.Strikers,
    ScytheFiends: CardIds.ScytheFiends,
    Firedancer: CardIds.Firedancer,
    MagmaHurler: CardIds.MagmaHurler,
    Virtuoso: CardIds.Virtuoso,
    BoomBrothers: CardIds.BoomBrothers,
    GiantSlayer: CardIds.GiantSlayer,
    Moloch: CardIds.Moloch,
    TimelessOne: CardIds.TimelessOne,
    NoxTrooper: CardIds.NoxTrooper,
    ShadowMage: CardIds.ShadowMage,
    Executor: CardIds.Executor,
    MutatingFrenzy: CardIds.MutatingFrenzy,
    AshbonePyro: CardIds.AshbonePyro,
    Vulcan: CardIds.Vulcan,
    Battleship: CardIds.Battleship,
    GroveSpirit: CardIds.GroveSpirit,
    Shaman: CardIds.Shaman,
    Mauler: CardIds.Mauler,
    FathomLord: CardIds.FathomLord,
    Colossus: CardIds.Colossus,
    Spikeroot: CardIds.Spikeroot,
    Thornbark: CardIds.Thornbark,
    DeathRay: CardIds.DeathRay,
    EnergyParasite: CardIds.EnergyParasite,
    ParasiteSwarm: CardIds.ParasiteSwarm,
    LivingTower: CardIds.LivingTower,
    Nightcrawler: CardIds.Nightcrawler,
    Burrower: CardIds.Burrower,
    Drones: CardIds.Drones,
    ShadowInsect: CardIds.ShadowInsect,
    WinterWitch: CardIds.WinterWitch,
    SkyelfTemplar: CardIds.SkyelfTemplar,
    SkyelfCommander: CardIds.SkyelfCommander,
    SkyelfSage: CardIds.SkyelfSage,
    Tempest: CardIds.Tempest,
    MagmaFiend: CardIds.MagmaFiend,
    ShrineofMartyrs: CardIds.ShrineofMartyrs,
    IceShieldTower: CardIds.IceShieldTower,
    KoboldLaboratory: CardIds.KoboldLaboratory,
    DefenseTower: CardIds.DefenseTower,
    ShrineofWar: CardIds.ShrineofWar,
    MakeshiftTower: CardIds.MakeshiftTower,
    FireBomb: CardIds.FireBomb,
    MortarTower: CardIds.MortarTower,
    Werebeasts: CardIds.Werebeasts,
    Ghostspears: CardIds.Ghostspears,
    Razorleaf: CardIds.Razorleaf,
    SporeLauncher: CardIds.SporeLauncher,
    PrimevalWatcher: CardIds.PrimevalWatcher,
    TimeshifterSpirit: CardIds.TimeshifterSpirit,
    ShrineofMemory: CardIds.ShrineofMemory,
    WheelofGifts: CardIds.WheelofGifts,
    Tunnel: CardIds.Tunnel,
    FountainofRebirth: CardIds.FountainofRebirth,
    HealingWell: CardIds.HealingWell,
    DarkelfAssassins: CardIds.DarkelfAssassins,
    Ripper: CardIds.Ripper,
    UnstableDemon: CardIds.UnstableDemon,
    Overlord: CardIds.Overlord,
    CultistMaster: CardIds.CultistMaster,
    Necrofury: CardIds.Necrofury,
    Wrathgazer: CardIds.Wrathgazer,
    ShrineofGreed: CardIds.ShrineofGreed,
    Decomposer: CardIds.Decomposer,
    PortalNexus: CardIds.PortalNexus,
    FrostCrystal: CardIds.FrostCrystal,
    CorpseExplosion: CardIds.CorpseExplosion,
    RayofLight: CardIds.RayofLight,
    GlacierShell: CardIds.GlacierShell,
    Stronghold: CardIds.Stronghold,
    ResourceBooster: CardIds.ResourceBooster,
    AltarofChaos: CardIds.AltarofChaos,
    FurnaceofFlesh: CardIds.FurnaceofFlesh,
    Lifestealer: CardIds.Lifestealer,
    WarEagle: CardIds.WarEagle,
    ManaWing: CardIds.ManaWing,
    ShadowPhoenix: CardIds.ShadowPhoenix,
    FallenSkyelf: CardIds.FallenSkyelf,
    Scavenger: CardIds.Scavenger,
    FireStalker: CardIds.FireStalker,
    Swiftclaw: CardIds.Swiftclaw,
    FireDragon: CardIds.FireDragon,
    Dreadnought: CardIds.Dreadnought,
    AvatarofFrost: CardIds.AvatarofFrost,
    CannonTower: CardIds.CannonTower,
    CreepingParalysis: CardIds.CreepingParalysis,
    SkyfireDrake: CardIds.SkyfireDrake,
    PrimalDefender: CardIds.PrimalDefender,
    Dreadcharger: CardIds.Dreadcharger,
    SwampDrake: CardIds.SwampDrake,
    GiantWyrm: CardIds.GiantWyrm,
    FireWorm: CardIds.FireWorm,
    AuraofCorruption: CardIds.AuraofCorruption,
    PhaseTower: CardIds.PhaseTower,
    Grimvine: CardIds.Grimvine,
    DeepcoilWorm: CardIds.DeepcoilWorm,
    ShadowWorm: CardIds.ShadowWorm,
    RallyingBanner: CardIds.RallyingBanner,
    Thunderstorm: CardIds.Thunderstorm,
    Earthshaker: CardIds.Earthshaker,
    KoboldTrick: CardIds.KoboldTrick,
    Wallbreaker: CardIds.Wallbreaker,
    WardoftheNorth: CardIds.WardoftheNorth,
    NastySurprise: CardIds.NastySurprise,
    AuraofPain: CardIds.AuraofPain,
    AreaIceShield: CardIds.AreaIceShield,
    TowerofFlames: CardIds.TowerofFlames,
    FrostShard: CardIds.FrostShard,
    Maelstrom: CardIds.Maelstrom,
    NoxiousCloud: CardIds.NoxiousCloud,
    EnsnaringRoots: CardIds.EnsnaringRoots,
    ArmoredTower: CardIds.ArmoredTower,
    TermiteHill: CardIds.TermiteHill,
    JuiceTank: CardIds.JuiceTank,
    WorldbreakerGun: CardIds.WorldbreakerGun,
    CometCatcher: CardIds.CometCatcher,
    MorklayTrap: CardIds.MorklayTrap,
    RocketTower: CardIds.RocketTower,
    Spitfire: CardIds.Spitfire,
    ConstructionHut: CardIds.ConstructionHut,
    BreedingGrounds: CardIds.BreedingGrounds,
    VoidMaw: CardIds.VoidMaw,
    Mountaineer: CardIds.Mountaineer,
    IceBarrier: CardIds.IceBarrier,
    MarkoftheKeeper: CardIds.MarkoftheKeeper,
    HomeSoil: CardIds.HomeSoil,
    Infect: CardIds.Infect,
    Soulshatter: CardIds.Soulshatter,
    Parasite: CardIds.Parasite,
    Lifestream: CardIds.Lifestream,
    EmbalmersShrine: CardIds.EmbalmersShrine,
    HealingGardens: CardIds.HealingGardens,
    StoneofTorment: CardIds.StoneofTorment,
    Regrowth: CardIds.Regrowth,
    LavaField: CardIds.LavaField,
    GlyphofFrost: CardIds.GlyphofFrost,
    ShieldBuilding: CardIds.ShieldBuilding,
    BloodHealing: CardIds.BloodHealing,
    UnholyHero: CardIds.UnholyHero,
    Suppression: CardIds.Suppression,
    PlagueOld: CardIds.PlagueOld,
    MindControl: CardIds.MindControl,
    Mine: CardIds.Mine,
    RetreatingCircle: CardIds.RetreatingCircle,
    UnholyPower: CardIds.UnholyPower,
    Bloodthirst: CardIds.Bloodthirst,
    Mindweaver: CardIds.Mindweaver,
    VoodooShack: CardIds.VoodooShack,
    Backlash: CardIds.Backlash,
    AltarofNihil: CardIds.AltarofNihil,
    Voidstorm: CardIds.Voidstorm,
    BannerofGlory: CardIds.BannerofGlory,
    IceTornado: CardIds.IceTornado,
    Wildfire: CardIds.Wildfire,
    Ravage: CardIds.Ravage,
    Enlightenment: CardIds.Enlightenment,
    ShatterIce: CardIds.ShatterIce,
    Motivate: CardIds.Motivate,
    Hurricane: CardIds.Hurricane,
    UndeadArmy: CardIds.UndeadArmy,
    Revenge: CardIds.Revenge,
    LifeWeaving: CardIds.LifeWeaving,
    ChurchofNegation: CardIds.ChurchofNegation,
    CurseofOink: CardIds.CurseofOink,
    FiredancerPromo: CardIds.FiredancerPromo,
    JuggernautPromo: CardIds.JuggernautPromo,
    RazorleafPromo: CardIds.RazorleafPromo,
    SwampDrakePromo: CardIds.SwampDrakePromo,
    LyrishKnightPromo: CardIds.LyrishKnightPromo,
    ConstructPromo: CardIds.ConstructPromo,
    FallenSkyelfPromo: CardIds.FallenSkyelfPromo,
    HarvesterPromo: CardIds.HarvesterPromo,
    LightbladeAShadow: CardIds.LightbladeAShadow,
    StormsingerAFire: CardIds.StormsingerAFire,
    CoreDredgeAFrost: CardIds.CoreDredgeAFrost,
    NomadAFire: CardIds.NomadAFire,
    GladiatrixANature: CardIds.GladiatrixANature,
    SpiritHuntersANature: CardIds.SpiritHuntersANature,
    ThunderWagonAFire: CardIds.ThunderWagonAFire,
    AmazonAFrost: CardIds.AmazonAFrost,
    ForestElderANature: CardIds.ForestElderANature,
    Nightguard: CardIds.Nightguard,
    NoxCarrierAFire: CardIds.NoxCarrierAFire,
    SnapjawsAFire: CardIds.SnapjawsAFire,
    MatterMasteryANature: CardIds.MatterMasteryANature,
    NorthstarAFrost: CardIds.NorthstarAFrost,
    FrontierKeepAFrost: CardIds.FrontierKeepAFrost,
    BlasterCannonAFire: CardIds.BlasterCannonAFire,
    InfernalMachineAShadow: CardIds.InfernalMachineAShadow,
    RootNexusANature: CardIds.RootNexusANature,
    HowlingShrineANature: CardIds.HowlingShrineANature,
    SoulSplicerANature: CardIds.SoulSplicerANature,
    TimeVortexAShadow: CardIds.TimeVortexAShadow,
    BloodhornAShadow: CardIds.BloodhornAShadow,
    StoneTempestAFrost: CardIds.StoneTempestAFrost,
    CurseOrb: CardIds.CurseOrb,
    RageflameAFrost: CardIds.RageflameAFrost,
    OfferingANature: CardIds.OfferingANature,
    BanditLauncherAFire: CardIds.BanditLauncherAFire,
    GravitySurgeAFrost: CardIds.GravitySurgeAFrost,
    NetherWarpAFrost: CardIds.NetherWarpAFrost,
    DisenchantAShadow: CardIds.DisenchantAShadow,
    StoneShardsAFrost: CardIds.StoneShardsAFrost,
    CrystalFiendANature: CardIds.CrystalFiendANature,
    AggressorANature: CardIds.AggressorANature,
    StoneWarriorAFrost: CardIds.StoneWarriorAFrost,
    GrinderAShadow: CardIds.GrinderAShadow,
    GemeyeAShadow: CardIds.GemeyeAShadow,
    CommandosAShadow: CardIds.CommandosAShadow,
    BanditosANature: CardIds.BanditosANature,
    BanditStalkerAShadow: CardIds.BanditStalkerAShadow,
    WindhunterAShadow: CardIds.WindhunterAShadow,
    CorsairANature: CardIds.CorsairANature,
    GunnerAFire: CardIds.GunnerAFire,
    TortugunAFrost: CardIds.TortugunAFrost,
    SkydefenderAShadow: CardIds.SkydefenderAShadow,
    WaystationAFire: CardIds.WaystationAFire,
    ArtilleryAShadow: CardIds.ArtilleryAShadow,
    StoneLauncherAFrost: CardIds.StoneLauncherAFrost,
    StoneHurlerAFire: CardIds.StoneHurlerAFire,
    HammerfallANature: CardIds.HammerfallANature,
    DeepgorgeAFrost: CardIds.DeepgorgeAFrost,
    ScorchedEarthAFire: CardIds.ScorchedEarthAFire,
    VilebloodAFire: CardIds.VilebloodAFire,
    SlaverAFire: CardIds.SlaverAFire,
    TwilightMinionsAFire: CardIds.TwilightMinionsAFire,
    EnvenomAShadow: CardIds.EnvenomAShadow,
    EquilibriumAFrost: CardIds.EquilibriumAFrost,
    DeathgliderANature: CardIds.DeathgliderANature,
    MutatingManiacANature: CardIds.MutatingManiacANature,
    SkycatcherANature: CardIds.SkycatcherANature,
    NightshadePlantANature: CardIds.NightshadePlantANature,
    TwilightCreeperAFire: CardIds.TwilightCreeperAFire,
    AmiiRitualAFrost: CardIds.AmiiRitualAFrost,
    TwilightBombardAFire: CardIds.TwilightBombardAFire,
    HatecasterAShadow: CardIds.HatecasterAShadow,
    FleshbenderAShadow: CardIds.FleshbenderAShadow,
    WillzapperAFire: CardIds.WillzapperAFire,
    KnightOfChaosAFrost: CardIds.KnightOfChaosAFrost,
    IcefangRaptorAFire: CardIds.IcefangRaptorAFire,
    FireswornAFrost: CardIds.FireswornAFrost,
    SunReaverAFire: CardIds.SunReaverAFire,
    DryadANature: CardIds.DryadANature,
    DeepOneANature: CardIds.DeepOneANature,
    WitchclawsAShadow: CardIds.WitchclawsAShadow,
    FrostBiteAShadow: CardIds.FrostBiteAShadow,
    EarthenGiftAFire: CardIds.EarthenGiftAFire,
    UnityANature: CardIds.UnityANature,
    AmokAFire: CardIds.AmokAFire,
    PromiseofLifeANature: CardIds.PromiseofLifeANature,
    SecondChanceANature: CardIds.SecondChanceANature,
    Mo: CardIds.Mo,
    Viridya: CardIds.Viridya,
    RoganKayle: CardIds.RoganKayle,
    Ravenheart: CardIds.Ravenheart,
    LightbladeAFire: CardIds.LightbladeAFire,
    NorthstarANature: CardIds.NorthstarANature,
    MoPromo: CardIds.MoPromo,
    ViridyaPromo: CardIds.ViridyaPromo,
    RoganKaylePromo: CardIds.RoganKaylePromo,
    RavenheartPromo: CardIds.RavenheartPromo,
    StormsingerANature: CardIds.StormsingerANature,
    CoreDredgeAFire: CardIds.CoreDredgeAFire,
    FrontierKeepAFire: CardIds.FrontierKeepAFire,
    GravitySurgeAShadow: CardIds.GravitySurgeAShadow,
    AmiiRitualANature: CardIds.AmiiRitualANature,
    FrostBiteAFire: CardIds.FrostBiteAFire,
    NomadANature: CardIds.NomadANature,
    GladiatrixAShadow: CardIds.GladiatrixAShadow,
    ThunderWagonAShadow: CardIds.ThunderWagonAShadow,
    BlasterCannonAShadow: CardIds.BlasterCannonAShadow,
    InfernalMachineAFire: CardIds.InfernalMachineAFire,
    DisenchantANature: CardIds.DisenchantANature,
    ScorchedEarth: CardIds.ScorchedEarth,
    UnityAFrost: CardIds.UnityAFrost,
    ForestElderAShadow: CardIds.ForestElderAShadow,
    AmazonANature: CardIds.AmazonANature,
    SpiritHuntersAShadow: CardIds.SpiritHuntersAShadow,
    TortugunAFire: CardIds.TortugunAFire,
    BloodhornAFire: CardIds.BloodhornAFire,
    NightguardANature: CardIds.NightguardANature,
    GrinderAFire: CardIds.GrinderAFire,
    RageflameAFire: CardIds.RageflameAFire,
    RootNexusAFrost: CardIds.RootNexusAFrost,
    HowlingShrineAShadow: CardIds.HowlingShrineAShadow,
    EnvenomAFire: CardIds.EnvenomAFire,
    EquilibriumANature: CardIds.EquilibriumANature,
    PromiseofLifeAFrost: CardIds.PromiseofLifeAFrost,
    NoxCarrierAShadow: CardIds.NoxCarrierAShadow,
    SnapjawsAShadow: CardIds.SnapjawsAShadow,
    SoulSplicerAFire: CardIds.SoulSplicerAFire,
    TimeVortexAFrost: CardIds.TimeVortexAFrost,
    NetherWarpANature: CardIds.NetherWarpANature,
    OfferingAFrost: CardIds.OfferingAFrost,
    SecondChanceAShadow: CardIds.SecondChanceAShadow,
    CommandosAFrost: CardIds.CommandosAFrost,
    BanditosAFrost: CardIds.BanditosAFrost,
    BanditStalkerANature: CardIds.BanditStalkerANature,
    WindhunterANature: CardIds.WindhunterANature,
    CorsairAShadow: CardIds.CorsairAShadow,
    GunnerAShadow: CardIds.GunnerAShadow,
    BanditLauncherAShadow: CardIds.BanditLauncherAShadow,
    SkydefenderANature: CardIds.SkydefenderANature,
    WaystationAShadow: CardIds.WaystationAShadow,
    ArtilleryAFire: CardIds.ArtilleryAFire,
    StoneTempestAShadow: CardIds.StoneTempestAShadow,
    StoneShardsAFire: CardIds.StoneShardsAFire,
    CrystalFiendAFrost: CardIds.CrystalFiendAFrost,
    SandstormAFire: CardIds.SandstormAFire,
    AmokANature: CardIds.AmokANature,
    GemeyeANature: CardIds.GemeyeANature,
    AggressorAFrost: CardIds.AggressorAFrost,
    MatterMasteryAShadow: CardIds.MatterMasteryAShadow,
    StoneWarriorANature: CardIds.StoneWarriorANature,
    EarthenGiftAShadow: CardIds.EarthenGiftAShadow,
    StoneLauncherAShadow: CardIds.StoneLauncherAShadow,
    StoneHurlerAShadow: CardIds.StoneHurlerAShadow,
    HammerfallAFrost: CardIds.HammerfallAFrost,
    DeepgorgeAFire: CardIds.DeepgorgeAFire,
    SandstormAShadow: CardIds.SandstormAShadow,
    NorthlandDrakeAFire: CardIds.NorthlandDrakeAFire,
    BatarielAFire: CardIds.BatarielAFire,
    GrimBahirAFire: CardIds.GrimBahirAFire,
    IroncladAFrost: CardIds.IroncladAFrost,
    AbyssalWarderAFrost: CardIds.AbyssalWarderAFrost,
    SatanaelAFire: CardIds.SatanaelAFire,
    LostWarlordAFire: CardIds.LostWarlordAFire,
    BurrowRitualANature: CardIds.BurrowRitualANature,
    DeepOneAShadow: CardIds.DeepOneAShadow,
    StrangleholdAShadow: CardIds.StrangleholdAShadow,
    StrangleholdANature: CardIds.StrangleholdANature,
    PyromaniacAFrost: CardIds.PyromaniacAFrost,
    PyromaniacAFire: CardIds.PyromaniacAFire,
    KnightOfChaosAShadow: CardIds.KnightOfChaosAShadow,
    SatanaelAShadow: CardIds.SatanaelAShadow,
    FireswornAFire: CardIds.FireswornAFire,
    BurrowRitualAFire: CardIds.BurrowRitualAFire,
    DryadAFrost: CardIds.DryadAFrost,
    IncubatorAFire: CardIds.IncubatorAFire,
    WardensSigilANature: CardIds.WardensSigilANature,
    WardensSigilAFrost: CardIds.WardensSigilAFrost,
    KoboldIncAFrost: CardIds.KoboldIncAFrost,
    VolcanoAFire: CardIds.VolcanoAFire,
    IncubatorAShadow: CardIds.IncubatorAShadow,
    SylvanGateAFire: CardIds.SylvanGateAFire,
    NecroblasterAShadow: CardIds.NecroblasterAShadow,
    GrimBahirANature: CardIds.GrimBahirANature,
    LostWandererANature: CardIds.LostWandererANature,
    LostShadeAFrost: CardIds.LostShadeAFrost,
    LostDancer: CardIds.LostDancer,
    LostReaverAFire: CardIds.LostReaverAFire,
    LostVigilANature: CardIds.LostVigilANature,
    LostSpiritShipANature: CardIds.LostSpiritShipANature,
    LostGrigoriAShadow: CardIds.LostGrigoriAShadow,
    VilebloodANature: CardIds.VilebloodANature,
    SlaverAShadow: CardIds.SlaverAShadow,
    LostLauncherAFire: CardIds.LostLauncherAFire,
    LostDisruptorANature: CardIds.LostDisruptorANature,
    LostConverterAFrost: CardIds.LostConverterAFrost,
    LostBanestoneANature: CardIds.LostBanestoneANature,
    LostShadeAShadow: CardIds.LostShadeAShadow,
    LostReaverAShadow: CardIds.LostReaverAShadow,
    LostVigilAShadow: CardIds.LostVigilAShadow,
    ArchitectsCallAFrost: CardIds.ArchitectsCallAFrost,
    LostDisruptorAShadow: CardIds.LostDisruptorAShadow,
    LostWarlordAFrost: CardIds.LostWarlordAFrost,
    LostGrigoriAFire: CardIds.LostGrigoriAFire,
    TwilightCurseAShadow: CardIds.TwilightCurseAShadow,
    TwilightCurseAFire: CardIds.TwilightCurseAFire,
    ArchitectsCallAShadow: CardIds.ArchitectsCallAShadow,
    IroncladAFire: CardIds.IroncladAFire,
    SantaClaus: CardIds.SantaClaus,
    MutatingManiacAFire: CardIds.MutatingManiacAFire,
    KoboldIncAShadow: CardIds.KoboldIncAShadow,
    BatarielAShadow: CardIds.BatarielAShadow,
    EvocatorsWoeAShadow: CardIds.EvocatorsWoeAShadow,
    EvocatorsWoeANature: CardIds.EvocatorsWoeANature,
    IcefangRaptorAFrost: CardIds.IcefangRaptorAFrost,
    DyingBreedAShadow: CardIds.DyingBreedAShadow,
    DyingBreedANature: CardIds.DyingBreedANature,
    SylvanGateAFrost: CardIds.SylvanGateAFrost,
    LostWandererAFrost: CardIds.LostWandererAFrost,
    SunReaverANature: CardIds.SunReaverANature,
    ForestsVimAShadow: CardIds.ForestsVimAShadow,
    AbyssalWarderAFire: CardIds.AbyssalWarderAFire,
    LostDancerAFire: CardIds.LostDancerAFire,
    NorthlandDrakeAFrost: CardIds.NorthlandDrakeAFrost,
    IceAgeAFrost: CardIds.IceAgeAFrost,
    NightshadePlantAShadow: CardIds.NightshadePlantAShadow,
    TwilightMinionsANature: CardIds.TwilightMinionsANature,
    DeathgliderAFrost: CardIds.DeathgliderAFrost,
    SkycatcherAFrost: CardIds.SkycatcherAFrost,
    WillzapperAShadow: CardIds.WillzapperAShadow,
    TwilightCreeperAShadow: CardIds.TwilightCreeperAShadow,
    FleshbenderAFire: CardIds.FleshbenderAFire,
    NecroblasterANature: CardIds.NecroblasterANature,
    IceAgeANature: CardIds.IceAgeANature,
    VolcanoANature: CardIds.VolcanoANature,
    GlobalWarmingAFrost: CardIds.GlobalWarmingAFrost,
    GlobalWarmingAFire: CardIds.GlobalWarmingAFire,
    GlaciationAFire: CardIds.GlaciationAFire,
    GlaciationAFrost: CardIds.GlaciationAFrost,
    RevenantsBlessing: CardIds.RevenantsBlessing,
    RevenantsBlessingANature: CardIds.RevenantsBlessingANature,
    LostSpiritShipAFire: CardIds.LostSpiritShipAFire,
    LostBanestoneAFrost: CardIds.LostBanestoneAFrost,
    LostLauncherAFrost: CardIds.LostLauncherAFrost,
    HatecasterANature: CardIds.HatecasterANature,
    TwilightBombardAFrost: CardIds.TwilightBombardAFrost,
    LostConverter: CardIds.LostConverter,
    ProtectorsSealLS: CardIds.ProtectorsSealLS,
    ProtectorsSealT: CardIds.ProtectorsSealT,
    GreenPeaceAFire: CardIds.GreenPeaceAFire,
    GreenPeaceAFrost: CardIds.GreenPeaceAFrost,
    ForestsVimANature: CardIds.ForestsVimANature,
    InfernalChainANature: CardIds.InfernalChainANature,
    InfernalChainAFrost: CardIds.InfernalChainAFrost,
    ClusterExplosionAShadow: CardIds.ClusterExplosionAShadow,
    ClusterExplosionAFire: CardIds.ClusterExplosionAFire,
    LostEvocationAFire: CardIds.LostEvocationAFire,
    LostEvocationAFrost: CardIds.LostEvocationAFrost,
    TwilightPestilenceANature: CardIds.TwilightPestilenceANature,
    TwilightPestilenceAFrost: CardIds.TwilightPestilenceAFrost,
    BefallensCurseAShadow: CardIds.BefallensCurseAShadow,
    BefallensCurseAFire: CardIds.BefallensCurseAFire,
    CurseWell: CardIds.CurseWell,
    QueekQueek: CardIds.QueekQueek,
    Moon: CardIds.Moon,
    Jorne: CardIds.Jorne,
    WarlockAFire: CardIds.WarlockAFire,
    TreespiritAShadow: CardIds.TreespiritAShadow,
    MountainRowdyAShadow: CardIds.MountainRowdyAShadow,
    WitchclawsAFire: CardIds.WitchclawsAFire,
    WarlockAFrost: CardIds.WarlockAFrost,
    TreespiritANature: CardIds.TreespiritANature,
    LostPriest: CardIds.LostPriest,
    LostHorrorANature: CardIds.LostHorrorANature,
    LostDragonANature: CardIds.LostDragonANature,
    LostDragonAShadow: CardIds.LostDragonAShadow,
    BanditSpearmenAFire: CardIds.BanditSpearmenAFire,
    BanditSpearmenAFrost: CardIds.BanditSpearmenAFrost,
    MountainRowdyAFrost: CardIds.MountainRowdyAFrost,
    LostPriestAShadow: CardIds.LostPriestAShadow,
    TwilightBruteAFire: CardIds.TwilightBruteAFire,
    TwilightBruteANature: CardIds.TwilightBruteANature,
    LostHorrorAFire: CardIds.LostHorrorAFire,
    AbominationAFrost: CardIds.AbominationAFrost,
    AbominationAShadow: CardIds.AbominationAShadow,
    SoulhunterAFrost: CardIds.SoulhunterAFrost,
    SoulhunterAShadow: CardIds.SoulhunterAShadow,
    Deepfang: CardIds.Deepfang,
    DeepfangANature: CardIds.DeepfangANature,
    BanditLancerAShadow: CardIds.BanditLancerAShadow,
    BanditLancerANature: CardIds.BanditLancerANature,
    EarthkeeperAFrost: CardIds.EarthkeeperAFrost,
    EarthkeeperAFire: CardIds.EarthkeeperAFire,
    OracleMaskANature: CardIds.OracleMaskANature,
    RazorshardAFire: CardIds.RazorshardAFire,
    RazorshardANature: CardIds.RazorshardANature,
    TreefiendAShadow: CardIds.TreefiendAShadow,
    TreefiendANature: CardIds.TreefiendANature,
    OracleMaskAFire: CardIds.OracleMaskAFire,
    TheIncredibleMo: CardIds.TheIncredibleMo,
    FreneticAssaultANature: CardIds.FreneticAssaultANature,
    MumboJumboAShadow: CardIds.MumboJumboAShadow,
    MumboJumboAFire: CardIds.MumboJumboAFire,
    FreneticAssaultAShadow: CardIds.FreneticAssaultAShadow,
    NorthernKeepAFire: CardIds.NorthernKeepAFire,
    SunkenTempleAShadow: CardIds.SunkenTempleAShadow,
    EasterEgg: CardIds.EasterEgg,
    WintertideAFrost: CardIds.WintertideAFrost,
    WintertideAFire: CardIds.WintertideAFire,
    TwilightWarfareAFire: CardIds.TwilightWarfareAFire,
    AmiiMonument: CardIds.AmiiMonument,
    TwilightWarfareAShadow: CardIds.TwilightWarfareAShadow,
    SunkenTempleANature: CardIds.SunkenTempleANature,
    FlameCrystal: CardIds.FlameCrystal,
    EarthCrystal: CardIds.EarthCrystal,
    IceCrystal: CardIds.IceCrystal,
    DarkCrystal: CardIds.DarkCrystal,
    NorthernKeepAFrost: CardIds.NorthernKeepAFrost,
    InfectedTowerAFire: CardIds.InfectedTowerAFire,
    InfectedTowerAFrost: CardIds.InfectedTowerAFrost,
    RiotersRetreatANature: CardIds.RiotersRetreatANature,
    RiotersRetreatAFrost: CardIds.RiotersRetreatAFrost,
    GrinderAShadowPromo: CardIds.GrinderAShadowPromo,
    StoneShellAShadow: CardIds.StoneShellAShadow,
    StoneShellANature: CardIds.StoneShellANature,
    EtherealStormAFire: CardIds.EtherealStormAFire,
    EtherealStormAFrost: CardIds.EtherealStormAFrost,
    WarriorsDeathAFire: CardIds.WarriorsDeathAFire,
    WarriorsDeathAFrost: CardIds.WarriorsDeathAFrost,
    LordCyrian: CardIds.LordCyrian,
    BanditSorceressAFrost: CardIds.BanditSorceressAFrost,
    GirlPowerAFrost: CardIds.GirlPowerAFrost,
    GirlPower: CardIds.GirlPower,
    TwilightHagANature: CardIds.TwilightHagANature,
    BanditSorceressAFire: CardIds.BanditSorceressAFire,
    TwilightHagAFire: CardIds.TwilightHagAFire,
    Brannoc: CardIds.Brannoc,
    EliminatorAFire: CardIds.EliminatorAFire,
    EliminatorAFrost: CardIds.EliminatorAFrost,
    SantaClausWithPresents: CardIds.SantaClausWithPresents,
    AmiiPhantom: CardIds.AmiiPhantom,
    SnapjawsAFirePromo: CardIds.SnapjawsAFirePromo,
    FireSphere: CardIds.FireSphere,
    Plague: CardIds.Plague,
    AmiiPaladins: CardIds.AmiiPaladins,
    CoatOfProtectionAFrost: CardIds.CoatOfProtectionAFrost,
    CoatOfProtectionAShadow: CardIds.CoatOfProtectionAShadow,
    BanditSniper: CardIds.BanditSniper,
    BanditMinefield: CardIds.BanditMinefield,
    BanzaiLordAShadow: CardIds.BanzaiLordAShadow,
    BanzaiLordANature: CardIds.BanzaiLordANature,
    ManaWingPromo: CardIds.ManaWingPromo,
    BurningSpears: CardIds.BurningSpears,
    Transcendence: CardIds.Transcendence,
    WastelandTerrorAFire: CardIds.WastelandTerrorAFire,
    WastelandTerrorANature: CardIds.WastelandTerrorANature,
    TwilightCrawlers: CardIds.TwilightCrawlers,
    TwilightSlayersAFire: CardIds.TwilightSlayersAFire,
    TwilightSlayersAShadow: CardIds.TwilightSlayersAShadow,
    Tranquility: CardIds.Tranquility,
    EvilEye: CardIds.EvilEye,
    SanctuaryAFrost: CardIds.SanctuaryAFrost,
    SanctuaryANature: CardIds.SanctuaryANature,
    RavenArchwalker: CardIds.RavenArchwalker,
    WorldbreakerGunPromo: CardIds.WorldbreakerGunPromo,
    SleetStorm: CardIds.SleetStorm,
    Soulstone: CardIds.Soulstone,
    TectonicShift: CardIds.TectonicShift,
    GateOfAkylos: CardIds.GateOfAkylos,
    LostManabeast: CardIds.LostManabeast,
    BedrockAFrost: CardIds.BedrockAFrost,
    BedrockAShadow: CardIds.BedrockAShadow,
    Swarm: CardIds.Swarm,
    Icespike: CardIds.Icespike,
    Umbabwe: CardIds.Umbabwe,
    AmiiSentinel: CardIds.AmiiSentinel,
    EnergyCore: CardIds.EnergyCore,
    Skydancer: CardIds.Skydancer,
    Simulacrum: CardIds.Simulacrum,
    JornePromo: CardIds.JornePromo,
    TwilightArchers: CardIds.TwilightArchers,
    PowerShrine: CardIds.PowerShrine,
    BanditHut: CardIds.BanditHut,
    Molt: CardIds.Molt,
    Hellhound: CardIds.Hellhound,
    SpiritGate: CardIds.SpiritGate,
    FrostMagePromo: CardIds.FrostMagePromo,
    Devourer: CardIds.Devourer,
    TreasureWagon: CardIds.TreasureWagon,
    SundererPromo: CardIds.SundererPromo,
};